#!/bin/bash
errmsg="$(tput setaf 1)[!!]: Oops! Something went wrong and we're unable to complete your request at this time. Please try rebooting your device by performing a userspace reboot and try again. If the issue persists, please contact me for further assistance.$(tput sgr0)"
sleep 0.5
if launchctl load -w /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist; then
    echo "[1/3] softwareupdated is loaded."
else
    echo -e "$errmsg"
fi
sleep 0.5
if launchctl load -w /System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist; then
    echo "[2/3] softwareupdateservicesd is loaded."
else
    echo -e "$errmsg"
fi
sleep 0.5
if launchctl load -w /System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist; then
    echo "[3/3] OTATaskingAgent is loaded."
else
    echo "$errmsg"
fi
sleep 0.5
echo -e "Ahh! now i remember what update is.\n[i]: All done.\n[i]: No respring required."
killall -9 Preferences softwareupdated softwareupdateservicesd OTATaskingAgent 2>/dev/null #Supress "No matching processes belonging to you were found" error