#!/bin/sh

softwareupdated_plist="/System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist"
softwareupdateservicesd_plist="/System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist"
OTATaskingAgent_plist="/System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist"

errmsg="[!!]: Oops! Something went wrong.
Please try rebooting your device or performing a userspace reboot and try again. 
If the issue persists, please contact me for further assistance."

load_plist() {
    launchctl load -w "$1" && echo "[*] $2 Daemon is loaded." || echo -e "$errmsg"
    sleep 0.5
}

load_plist "$softwareupdated_plist" "softwareupdated"
load_plist "$softwareupdateservicesd_plist" "Software Update Service"
load_plist "$OTATaskingAgent_plist" "OTATaskingAgent"

echo -e "Ahh! now I remember what update is.
[i]: All done.
[i]: No respring required, but you can if you want to."
