#!/bin/bash
errmsg="$(tput setaf 1)[!!]: Oops! Something went wrong.\nPlease try rebooting your device or performing a userspace reboot and try again. 
\nIf the issue persists, please contact me for further assistance.$(tput sgr0)"
launchctl load -w /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist && echo "[1/3] Software Updated Daemon is loaded." || echo -e "$errmsg" ; sleep 0.5
launchctl load -w /System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist && echo "[2/3] Software Update Services Daemon is loaded." || echo -e "$errmsg" ; sleep 0.5
launchctl load -w /System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist && echo "[3/3] OTATaskingAgent Daemon is loaded." || echo "$errmsg" ; sleep 0.5
echo -e "Ahh! now i remember what update is.\n[i]: All done.\n[i]: No respring required, but you can if you want to."